### ISSUE TITLE
NeoForge Version

### ISSUE THREAD

**Issue by tmschorr** [Jan-Marvin/simple-auto-fishing#2]
Hi, could you create a NeoForge version for your auto fishing mod?

**Comment by Jan-Marvin** [comment]
I will look into it.

**Comment by Jan-Marvin** [comment]
It was quite easy to port, you can download it [here](https://github.com/Jan-Marvin/simple-auto-fishing/blob/master/README.md).

**Comment by tmschorr** [comment]
Thank you very much
