### ISSUE TITLE
error

### ISSUE THREAD

**Issue by youngmini11** [Jan-Marvin/simple-auto-fishing#3]
When fishing, the delay time between collecting an item and throwing the fishing rod again is too short, so you end up throwing the fishing rod at a flying item.

As a result, the fishing rod gets caught on an item and the next fishing cannot proceed.

(( 1.21 fabric using ))

**Comment by youngmini11** [comment]
추가로 이 현상은 인벤토리가 가득찼을때 발생합니다.

**Comment by youngmini11** [comment]
> When fishing, the delay time between collecting an item and throwing the fishing rod again is too short, so you end up throwing the fishing rod at a flying item.

As a result, the fishing rod gets caught on an item and the next fishing cannot proceed.

**Comment by Jan-Marvin** [comment]
It seems I cannot reproduce this behavior.
In the rain, with a Lure 3 and a Luck of the Sea 3 rod, it works for me.
From far away, on a tree, or right by the sea.

Do you have other mods or are you not using the default tick rate?
